### ISSUE TITLE
dynamic_with_cors

### ISSUE THREAD

**Issue by martinthomson** [fedidcg/CrossSiteCookieAccessCredential#19]
This label really doesn't explain itself very well, nor does the supporting explanation.  I have two requests:

1. As this features prominently, explain what it is for.
2. Pick a better name that reflects the *purpose* of the value, rather than *how* it achieves that purpose.

**Comment by bvandersloot-mozilla** [comment]
I'll rename both dynamic_via_cors and origin_allowlist to be in relation to their purpose. The following paragraph would replace the start of "Identity Provider API, Creating a Credential" and gives their new names and reasoning.

>The identity provider needs to specify at least one of two arguments when creating the credential (`effectiveOrigins` or `effectiveQueryURL`) to tell the browser which origins the credential is [effective](https://w3c.github.io/webappsec-credential-management/#credential-effective) for. A list of origins may be provided to `effectiveOrigins` if the list of relying parties may be made public and is known ahead of time. If the list of relying parties is dynamic or private, the identity provider may provide an HTTP-endpoint that will respond successfully to a CORS request from the relying party with `Sec-Fetch-Dest: web-identity` if the relying party can use the credential at that time.

**Comment by martinthomson** [comment]
Sounds reasonable.  Perhaps..

> [...] the identity provider may provide an HTTP endpoint *with `effectiveQueryURL`*. That HTTP endpoint needs to respond successfully [...]
