### ISSUE TITLE
Missing required 'clientId' member of IdentityProviderConfig

### ISSUE THREAD

**Issue by philsmart** [fedidcg/CrossSiteCookieAccessCredential#21]
Just trying to follow the example in the [slides](https://docs.google.com/presentation/d/1F-upvc5F0u63U_QX9nBacJRmEmHe1aE-J7LPhlKrheY/edit?usp=sharing) in FF nightly 127. I am not sure if I need to toggle a flag etc. but I can not get it to use the n.c.get API without supplying it all the required fields of IdentityProviderConfig. Possibly this isn't something I can test yet?

**Comment by bvandersloot-mozilla** [comment]
This can't be tested yet, unfortunately. I will update the group once it can!

**Comment by philsmart** [comment]
No worries. Thanks!
