### ISSUE TITLE
Update explainer to reflect how IdentityCredentials are created by IdP in the demo page

### ISSUE THREAD

**Issue by ekovac** [fedidcg/CrossSiteCookieAccessCredential#35]
Currently the [explainer examples for the IdP side](https://github.com/fedidcg/CrossSiteCookieAccessCredential?tab=readme-ov-file#identity-provider-api-creating-a-credential) use `navigator.credentials.create()` to instantiate a lightweight credential before storing; this doesn't align with the [demonstration page](https://lightweight-fedcm-provider.glitch.me/) or, presumably, the prototype implementation in Firefox Nightly. In that demonstration a new IdentityCredential is created using `new`. Is this the intention? Should both mechanisms for creating an IdentityCredential for storage be supported? Which would be more consistent with the Credential Management API family?

**Comment by ekovac** [comment]
The alternative of course is to update the demonstration page to match the explainer, but it's unclear which one is correct :)

**Comment by bvandersloot-mozilla** [comment]
Both should be supported IMO to be consistent with other Credential types, e.g. for PasswordCredential we have [create](https://w3c.github.io/webappsec-credential-management/#dom-passwordcredential-create-slot) and [new](https://w3c.github.io/webappsec-credential-management/#dom-passwordcredential-passwordcredential-data).

**Comment by ekovac** [comment]
Closing this out; clarifying this probably doesn't need to be in the explainer.

**Comment by bvandersloot-mozilla** [comment]
:+1:, but it is good a good catch. Something like the `webidl` is maybe a little out of scope for the explainer but would resolve this confusion. I'll think about including it.

**Comment by bvandersloot-mozilla** [comment]
@ekovac : also, FYI: [here is Firefox's webidl!](https://searchfox.org/mozilla-central/rev/a85b25946f7f8eebf466bd7ad821b82b68a9231f/dom/webidl/IdentityCredential.webidl)
